owner: ccmbioinfo
repo: status

sites:
  - name: Main site
    url: https://ccm.sickkids.ca
  - name: EpigenCentral
    url: https://epigen.ccm.sickkids.ca

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.ccm.sickkids.ca
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/ccmbioinfo/.github/master/profile/logo.png
  name: SickKids CCM web application status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: About us
      href: https://ccm.sickkids.ca

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
